import { ButtonLink } from "@/components/button-link";
import { CommitteeCard, EventCard, ProjectCard, WorkshopCard } from "@/components/cards";
import { SectionHeading } from "@/components/section-heading";
import { committee, events, projects, workshops } from "@/lib/site-data";

export default function Home() {
  return <>
    <section className="hero-grid"><div className="hero-content site-shell grid gap-10 py-18 lg:grid-cols-[1.2fr_.8fr] lg:items-center sm:py-28"><div><p className="eyebrow">University of Greenwich · Cybersecurity Society</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold tracking-tight text-white sm:text-7xl">Learn security.<br /><span className="text-[#20ff62]">Build confidence.</span><br />Make an impact.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">GreCyberSec is a practical, welcoming community for students who want to understand and shape a more secure digital world.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/contact">Join the society</ButtonLink><ButtonLink href="/events" variant="secondary">Explore events</ButtonLink></div></div><div className="hero-logo"><Image src="/images/grecybersec-logo.jpg" alt="GreCyberSec code mark" width={1532} height={1532} priority sizes="(min-width: 1024px) 32vw, 100vw" /></div></div></section>
    <section className="site-shell py-16 sm:py-24"><div className="grid gap-10 lg:grid-cols-[1fr_1.25fr] lg:items-end"><SectionHeading eyebrow="Who we are" title="A place to learn by doing." intro="From your first security concept to your next technical challenge, we create thoughtful spaces for exploration, collaboration and responsible practice." /><div className="grid gap-4 sm:grid-cols-2"><div className="card"><p className="text-3xl font-semibold text-[#20ff62]">Hands-on</p><p className="mt-2 text-slate-300">Workshops designed to turn curiosity into skill.</p></div><div className="card"><p className="text-3xl font-semibold text-[#20ff62]">Community-led</p><p className="mt-2 text-slate-300">A supportive network across every level of experience.</p></div></div></div></section>
    <section className="section-alt"><div className="site-shell py-16 sm:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="What’s next" title="Upcoming events" intro="Open sessions for students who want to meet, learn and practise." /><ButtonLink href="/events" variant="text">All events</ButtonLink></div><div className="mt-10 grid gap-5 md:grid-cols-3">{events.map((event) => <EventCard event={event} key={event.title} />)}</div></div></section>
    <section className="site-shell py-16 sm:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="Skills studio" title="Workshops for every starting point" intro="Clear, structured sessions on the areas that matter in modern security." /><ButtonLink href="/workshops" variant="text">View workshops</ButtonLink></div><div className="mt-10 grid gap-5 md:grid-cols-2">{workshops.map((workshop) => <WorkshopCard workshop={workshop} key={workshop.title} />)}</div></section>
    <section className="section-alt"><div className="site-shell grid gap-10 py-16 sm:grid-cols-[1.2fr_1fr] sm:items-center sm:py-24"><div><p className="eyebrow">Capture the Flag</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Challenge your thinking, responsibly.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-300">Our CTF activities turn theory into puzzles. Work with others, document your approach and practise within clear ethical boundaries.</p><div className="mt-7"><ButtonLink href="/ctf">Discover CTF</ButtonLink></div></div><div className="card border-[#20ff62]/50"><p className="eyebrow">Our approach</p><ol className="mt-5 space-y-4 text-slate-200"><li><span className="mr-3 text-[#20ff62]">01</span>Learn the foundations</li><li><span className="mr-3 text-[#20ff62]">02</span>Work through challenges together</li><li><span className="mr-3 text-[#20ff62]">03</span>Share methods, not harm</li></ol></div></div></section>
    <section className="site-shell py-16 sm:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="Student work" title="Projects with purpose" intro="Small, focused projects that investigate real security questions." /><ButtonLink href="/projects" variant="text">All projects</ButtonLink></div><div className="mt-10 grid gap-5 md:grid-cols-3">{projects.map((project) => <ProjectCard project={project} key={project.title} />)}</div></section>
    <section className="section-alt"><div className="site-shell py-16 sm:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="The people" title="Meet the committee" intro="The team coordinating a thoughtful, student-centred programme." /><ButtonLink href="/committee" variant="text">Meet the team</ButtonLink></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{committee.map((member) => <CommitteeCard member={member} key={member.role} />)}</div></div></section>
  </>;
}
import Image from "next/image";
