import { ButtonLink } from "@/components/button-link";
import { CommitteeCard } from "@/components/cards";
import { SectionHeading } from "@/components/section-heading";
import { committee } from "@/lib/site-data";

export default function Home() {
  return <>
    <section className="hero-grid"><div className="hero-content site-shell grid gap-10 py-18 lg:grid-cols-[1.2fr_.8fr] lg:items-center sm:py-28"><div className="hero-copy"><span className="hero-status">Student-led security community</span><p className="eyebrow mt-6">University of Greenwich · Cybersecurity Society</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold tracking-tight text-white sm:text-7xl">Learn security.<br /><span className="text-[#20ff62]">Build confidence.</span><br />Make an impact.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">GreCyberSec is a practical, welcoming community for students who want to understand and shape a more secure digital world.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/contact">Join the society</ButtonLink><ButtonLink href="/courses" variant="secondary">Explore courses</ButtonLink></div></div><div className="hero-logo"><Image src="/images/grecybersec-logo.jpg" alt="GreCyberSec code mark" width={1532} height={1532} loading="eager" sizes="(min-width: 1024px) 32vw, 100vw" /></div></div></section>
    <section className="site-shell py-16 sm:py-24"><div className="grid gap-10 lg:grid-cols-[1fr_1.25fr] lg:items-end"><SectionHeading eyebrow="Who we are" title="A place to learn by doing." intro="From your first security concept to your next technical challenge, we create thoughtful spaces for exploration, collaboration and responsible practice." /><div className="grid gap-4 sm:grid-cols-2"><div className="card"><p className="text-3xl font-semibold text-[#20ff62]">Practical</p><p className="mt-2 text-slate-300">Learning opportunities designed to turn curiosity into skill.</p></div><div className="card"><p className="text-3xl font-semibold text-[#20ff62]">Community-led</p><p className="mt-2 text-slate-300">A supportive network across every level of experience.</p></div></div></div></section>
    <section className="section-alt"><div className="site-shell py-16 sm:py-24"><div className="notice-panel max-w-3xl"><p className="eyebrow">Programme update</p><h2 className="mt-3 text-3xl font-semibold text-white">Events are coming soon.</h2><p className="mt-4 leading-7 text-slate-300">The events programme is being prepared. Confirmed sessions and joining details will be published here once ready.</p><div className="mt-6"><ButtonLink href="/events" variant="secondary">Event updates</ButtonLink></div></div></div></section>
    <section className="site-shell py-16 sm:py-24"><div className="notice-panel max-w-3xl"><p className="eyebrow">Programme update</p><h2 className="mt-3 text-3xl font-semibold text-white">Projects are coming soon.</h2><p className="mt-4 leading-7 text-slate-300">The project programme is being prepared. Approved opportunities and details will be published here once ready.</p><div className="mt-6"><ButtonLink href="/projects" variant="secondary">Project updates</ButtonLink></div></div></section>
    <section className="section-alt"><div className="site-shell py-16 sm:py-24"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="The people" title="Meet the committee" intro="The team coordinating a thoughtful, student-centred programme." /><ButtonLink href="/committee" variant="text">Meet the team</ButtonLink></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{committee.map((member) => <CommitteeCard member={member} key={member.role} />)}</div></div></section>
  </>;
}
import Image from "next/image";
